---

- name: shutdown services
  ansible.builtin.service:
    name: apparmor
    state: "{{ apparmor_state }}"
    enabled: "{{ apparmor_enabled }}"
  failed_when: false

- name: teardown
  ansible.builtin.command: |
    aa-teardown
  register: teardown
  failed_when: false
  changed_when: false

- name: remove apparmor packages
  ansible.builtin.package:
    name: [ apparmor ]
    state: absent
  when:
    - not apparmor_installed

- name: remove apparmor-related files or directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apparmor
    - /etc/apparmor.d
    - /etc/rcS.d/S01apparmor
    - /etc/rcS.d/K01apparmor
    - /etc/init.d/apparmor
    - /usr/lib/apparmor
    - /var/lib/snapd/apparmor
    - /var/cache/apparmor
    - /etc/systemd/system/apparmor.service
  when:
    - not apparmor_installed

...
